### PR TITLE
Canvas

### PR DESCRIPTION
**Pull request by fasterius**

### CODE REVIEW

**Review by verku — APPROVED** [review]
This looks super good! I am going to add a few commits to fix some small issues I spotted related to the new website and its layout, so it would be great if you could wait a few more days before merging. 

One point that we might want to talk about is that some pages are placed in a common module where the ordering doesn't make logical sense. Specifically, when I'm on the "Introduction" page, and click "Next", I end up on the "Schedule" page, and from there "Next" leads to the "Take down" page. Maybe each of them could be in their own module to avoid that?

**Comment by fasterius** [comment]
Thanks for the additions! Regarding pressing "Next": that goes to the next page, regardless of module (and it goes across modules), so putting those you mention into separate modules won't do anything for this. One could remove them from the module list entirely and instead put them in the navigation bar, if we think that's better.

**Comment by verku** [comment]
Maybe it's better to move the Schedule to the Navigation bar, the other items are fine where they are, I would think.

**Review by johnne — APPROVED** [review]
Great work!

**Pull request merged**
