### PR TITLE
Jupyter tutorial

### PR DESCRIPTION
**Pull request by johnne**
This PR has relatively large rewrites to the jupyter tutorial. Mainly it changes the "Case study" section to more closely resemble the output from the Rmarkdown notebook and adds text about integration with Snakemake. In addition, the NBConda extension has been removed to make way for the unofficial Jupyter extensions (`jupyter_contrib_nbextensions`)

### CODE REVIEW

**Review by fasterius — APPROVED** [review]
Looks good to me! I checked that your new environment file was correct with the new setup instructions, but I think it seems fine - could you double-check before you merge into devel?

**Review by verku — APPROVED** [review]
This looks great, good work!

I only have one suggestion. Why don't we move the integration with Snakemake (from "Integrating the notebook into the workflow" on) to the Extra material? Otherwise, the Jupyter tutorial is dependent on the Snakemake tutorial, which some people (e.g. in our internal courses) may choose to skip.

**Comment by fasterius** [comment]
> I only have one suggestion. Why don't we move the integration with Snakemake (from "Integrating the notebook into the workflow" on) to the Extra material? Otherwise, the Jupyter tutorial is dependent on the Snakemake tutorial, which some people (e.g. in our internal courses) may choose to skip.

I agree, that is a good idea!

**Comment by johnne** [comment]
Thanks for the input! That's a good idea about the integration...

**Pull request merged**
